### ISSUE TITLE
recursive clone of eigen library not working

### ISSUE THREAD

**Issue by f-brinkmann** [pmp-library/pmp-library#103] opened 2022-04-14 11:15 UTC
**Describe the bug**
The cloning stops when trying to clone the eigen library. Other external repository were cloned correctly. Maybe the link to the eigen repository needs to be updated. It might be broken (can't be followed from https://github.com/pmp-library/pmp-library/tree/master/external)

**To Reproduce**
`git clone --recursive https://github.com/pmp-library/pmp-library.git`

**Expected behavior**
Complete recursive clone

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by dsieger** [comment] 2022-04-14 19:48
Hi, looks like a temporary issue to me. Just did a fresh clone and everything works fine. Closing for now, please shout if the issue is persistent.

**Closed by dsieger** 2022-04-14 19:48 UTC
